### ISSUE TITLE
Enhancement Request: Allow forwarding custom attributes

### ISSUE THREAD

**Issue by mpyw** [duskmoon314/utility-rs#9]
## Problem

Currently, type utility macros doesn't forward custom attributes like `#[dummy(...)]` to the generated structs. This limitation prevents users from utilizing important custom attributes in derived structures.

## Current Behavior

```rust
#[derive(Omit)]
#[omit(arg(ident = EntityAttributes, fields(id), derive(Debug, Dummy)))]
pub struct Entity {
    id: i32,
    pub name: String,
    #[dummy(faker = "ExampleUrl()")]
    pub thumbnail_url: Url,
}
```

The `#[dummy(...)]` attribute is lost in the generated `EntityAttributes` struct.

## Proposal

Add a `forward_attrs` option to the type utility macros:

```rust
#[derive(Omit)]
#[omit(arg(
    ident = EntityAttributes, 
    fields(id), 
    derive(Debug, Dummy),
    forward_attrs(dummy)
))]
pub struct Entity {
    id: i32,
    pub name: String,
    #[dummy(faker = "ExampleUrl()")]
    pub thumbnail_url: Url,
}
```

**Comment by duskmoon314** [comment]
This seems like a bug since I want to pass the attributes by default. I will try to find out why ASAP.

**Comment by duskmoon314** [comment]
Oh, I set `forward_attrs(allow, doc, cfg)` as the example of `darling`'s documents. This prevents custom attributes from being forwarded.

**Comment by duskmoon314** [comment]
I remember why I set it that way: This prevents forward `pick` to `omit`.

I'm trying to support this enhancement.

**Comment by duskmoon314** [comment]
An implementation is in the PR#10. I think it mostly fixes this issue. Could you please check the changes of README.md, lib.rs, and tests, then point out whether there is something I haven't considered?

**Comment by mpyw** [comment]
The pull request you submitted looks good, but since I am still relatively new to Rust and don't feel confident enough to conduct a thorough review, I would like to recommend my former colleague @siketyan, who is more experienced with Rust, as the reviewer.

**Comment by duskmoon314** [comment]
A new version (v0.0.4) is released and includes this enhancement.
